#!/bin/sh

SPEAKER_ID="$(wpctl status | grep speaker | grep -oP '\d+(?=\.)' | head -1)"

case $BLOCK_BUTTON in
	1) wpctl set-mute $SPEAKER_ID toggle ;;
	3) pwvucontrol ;;
	4) wpctl set-volume $SPEAKER_ID 10%+ ;;
	5) wpctl set-volume $SPEAKER_ID 10%- ;;
esac

vol="$(wpctl get-volume $SPEAKER_ID)" # get vol of speaker

[ "$vol" != "${vol%\[MUTED\]}" ] && echo " 󰝟 " && exit

vol="${vol#Volume: }"

split() {
	# For ommiting the . without calling and external program.
	IFS=$2
	set -- $1
	printf '%s' "$@"
}

vol="$(printf "%.0f" "$(split "$vol" ".")")"

case 1 in
	$((vol >= 70)) ) icon=" 󰕾 " ;;
	$((vol >= 30)) ) icon=" 󰖀 " ;;
	$((vol >= 1)) ) icon=" 󰕿 " ;;
	* ) echo " 󰝟 " && exit ;;
esac

# echo "$icon$vol%"
echo "$icon" # no volume readout, just icon
