#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "This Month" "$(cal | sed "s/\<$(date +'%e'|tr -d ' ')\>/<b><span color='red'>&<\/span><\/b>/")" #&& notify-send "Appointments" "$(calcurse -d3)" ;;
esac


date "+ %H:%M:%S | %Y %b %d - %a "
