#!/bin/sh

case $BLOCK_BUTTON in
	1) wpctl set-mute @DEFAULT_SOURCE@ toggle ;; # 156 is speaker
	3) pwvucontrol ;;
esac

vol="$(timeout 1 wpctl get-volume @DEFAULT_SOURCE@)" # get vol of mic

if [ "$(timeout 1 cat /proc/asound/card1/pcm0p/sub0/status 2>/dev/null)" != 'closed' ] ; then
	[ "$vol" != "${vol%\[MUTED\]}" ] && echo " 󰍭 " || echo " 󰍬 "
else
	echo ""
fi 
